model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false # Note: different from the one we trained before
    conditioning_key: crossattn
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [1] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [10000000000000] # incredibly large number to prevent corner cases
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 0
    num_val_workers: 0
    train:
      target: ldm.data.simple.hf_dataset
      params:
        name: imagefolder
        data_dir: "../dataset"
        image_transforms:
          - target: torchvision.transforms.Resize
            params:
              size: [512, 1024]
          - target: torchvision.transforms.RandomHorizontalFlip
          - target: torchvision.transforms.RandomVerticalFlip
    validation:
      target: ldm.data.simple.TextOnly
      params:
        captions:
          - "A planet cylindrical projection texture map of a celestial landscape punctuated by numerous craters and strewn with icy boulders, reflecting minimal sunlight due to its location in the outer solar system. fiction"
          - "A planet cylindrical projection texture map of a rugged, reddish landscape strewn with iron-rich rocks under a dusty, thin atmosphere, with towering volcanoes and deep, ancient riverbeds hinting at a geologically active past. NASA"
          - "A planet cylindrical projection texture map of a rugged, greenish landscape strewn with copper-rich rocks under a dusty, thin atmosphere, with towering volcanoes and deep, ancient riverbeds hinting at a geologically active past. NASA"
          - "A planet cylindrical projection texture map a dense, swirling atmosphere filled with brightly colored bands of clouds, composed mainly of hydrogen and helium, with intermittent, turbulent storm systems such as the Great Purple Spot. NASA"
        output_size: [512, 1024]
        n_gpus: 2

lightning:
  find_unused_parameters: False

  modelcheckpoint:
    params:
      every_n_train_steps: 200
      save_top_k: -1
      monitor: null

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_all_val: True
        log_images_kwargs:
          use_ema_scope: True
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 4
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
